// Code generated by protoc-gen-go.
// source: proto/gifcreator.proto
// DO NOT EDIT!

/*
Package renderdemo is a generated protocol buffer package.

It is generated from these files:
	proto/gifcreator.proto
	proto/render.proto

It has these top-level messages:
	StartJobRequest
	StartJobResponse
	GetJobRequest
	GetJobResponse
	RenderRequest
	RenderResponse
*/
package renderdemo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product int32

const (
	Product_UNKNOWN_PRODUCT Product = 0
	Product_GRPC            Product = 1
	Product_KUBERNETES      Product = 2
	Product_GO              Product = 3
)

var Product_name = map[int32]string{
	0: "UNKNOWN_PRODUCT",
	1: "GRPC",
	2: "KUBERNETES",
	3: "GO",
}
var Product_value = map[string]int32{
	"UNKNOWN_PRODUCT": 0,
	"GRPC":            1,
	"KUBERNETES":      2,
	"GO":              3,
}

func (x Product) String() string {
	return proto.EnumName(Product_name, int32(x))
}
func (Product) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetJobResponse_Status int32

const (
	GetJobResponse_UNKNOWN_STATUS GetJobResponse_Status = 0
	GetJobResponse_PENDING        GetJobResponse_Status = 1
	GetJobResponse_DONE           GetJobResponse_Status = 2
	GetJobResponse_FAILED         GetJobResponse_Status = 3
)

var GetJobResponse_Status_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "PENDING",
	2: "DONE",
	3: "FAILED",
}
var GetJobResponse_Status_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"PENDING":        1,
	"DONE":           2,
	"FAILED":         3,
}

func (x GetJobResponse_Status) String() string {
	return proto.EnumName(GetJobResponse_Status_name, int32(x))
}
func (GetJobResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type StartJobRequest struct {
	// TODO(light): what scene parameters do we want to give?
	Name          string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProductToPlug Product `protobuf:"varint,2,opt,name=product_to_plug,json=productToPlug,enum=renderdemo.Product" json:"product_to_plug,omitempty"`
}

func (m *StartJobRequest) Reset()                    { *m = StartJobRequest{} }
func (m *StartJobRequest) String() string            { return proto.CompactTextString(m) }
func (*StartJobRequest) ProtoMessage()               {}
func (*StartJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartJobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartJobRequest) GetProductToPlug() Product {
	if m != nil {
		return m.ProductToPlug
	}
	return Product_UNKNOWN_PRODUCT
}

type StartJobResponse struct {
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *StartJobResponse) Reset()                    { *m = StartJobResponse{} }
func (m *StartJobResponse) String() string            { return proto.CompactTextString(m) }
func (*StartJobResponse) ProtoMessage()               {}
func (*StartJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StartJobResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetJobRequest struct {
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *GetJobRequest) Reset()                    { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()               {}
func (*GetJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetJobRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type GetJobResponse struct {
	Status GetJobResponse_Status `protobuf:"varint,1,opt,name=status,enum=renderdemo.GetJobResponse_Status" json:"status,omitempty"`
	// World-readable URL for created image.
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
}

func (m *GetJobResponse) Reset()                    { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string            { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()               {}
func (*GetJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetJobResponse) GetStatus() GetJobResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetJobResponse_UNKNOWN_STATUS
}

func (m *GetJobResponse) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*StartJobRequest)(nil), "renderdemo.StartJobRequest")
	proto.RegisterType((*StartJobResponse)(nil), "renderdemo.StartJobResponse")
	proto.RegisterType((*GetJobRequest)(nil), "renderdemo.GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "renderdemo.GetJobResponse")
	proto.RegisterEnum("renderdemo.Product", Product_name, Product_value)
	proto.RegisterEnum("renderdemo.GetJobResponse_Status", GetJobResponse_Status_name, GetJobResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GifCreator service

type GifCreatorClient interface {
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
}

type gifCreatorClient struct {
	cc *grpc.ClientConn
}

func NewGifCreatorClient(cc *grpc.ClientConn) GifCreatorClient {
	return &gifCreatorClient{cc}
}

func (c *gifCreatorClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := grpc.Invoke(ctx, "/renderdemo.GifCreator/StartJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gifCreatorClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := grpc.Invoke(ctx, "/renderdemo.GifCreator/GetJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GifCreator service

type GifCreatorServer interface {
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
}

func RegisterGifCreatorServer(s *grpc.Server, srv GifCreatorServer) {
	s.RegisterService(&_GifCreator_serviceDesc, srv)
}

func _GifCreator_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GifCreatorServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/renderdemo.GifCreator/StartJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GifCreatorServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GifCreator_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GifCreatorServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/renderdemo.GifCreator/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GifCreatorServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GifCreator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "renderdemo.GifCreator",
	HandlerType: (*GifCreatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _GifCreator_StartJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _GifCreator_GetJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gifcreator.proto",
}

func init() { proto.RegisterFile("proto/gifcreator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0x51, 0x8f, 0x93, 0x40,
	0x10, 0xc7, 0x0f, 0xee, 0xe4, 0xda, 0xd1, 0xa3, 0x9b, 0xb9, 0x68, 0xce, 0x3b, 0x1f, 0x4e, 0x1e,
	0xcc, 0xe9, 0x03, 0x26, 0xf5, 0xc9, 0xf8, 0x70, 0xde, 0x15, 0x24, 0xb5, 0x06, 0xc8, 0x02, 0x31,
	0xf1, 0x85, 0x40, 0xd9, 0x12, 0x1a, 0xda, 0xc5, 0x65, 0xf9, 0x26, 0x7e, 0x09, 0xbf, 0xa5, 0x11,
	0x68, 0x8a, 0xa6, 0x7d, 0xdb, 0xcc, 0xfe, 0xe6, 0x3f, 0x33, 0xff, 0x19, 0x78, 0x51, 0x09, 0x2e,
	0xf9, 0xfb, 0xbc, 0x58, 0x2d, 0x05, 0x4b, 0x24, 0x17, 0x66, 0x1b, 0x40, 0x10, 0x6c, 0x9b, 0x31,
	0x91, 0xb1, 0x0d, 0x37, 0x52, 0x98, 0x04, 0x32, 0x11, 0xf2, 0x2b, 0x4f, 0x29, 0xfb, 0xd9, 0xb0,
	0x5a, 0x22, 0xc2, 0xd9, 0x36, 0xd9, 0xb0, 0x2b, 0xe5, 0x56, 0xb9, 0x1b, 0xd3, 0xf6, 0x8d, 0x9f,
	0x60, 0x52, 0x09, 0x9e, 0x35, 0x4b, 0x19, 0x4b, 0x1e, 0x57, 0x65, 0x93, 0x5f, 0xa9, 0xb7, 0xca,
	0x9d, 0x3e, 0xbd, 0x34, 0xf7, 0x62, 0xa6, 0xdf, 0x21, 0xf4, 0xa2, 0x67, 0x43, 0xee, 0x97, 0x4d,
	0x6e, 0xbc, 0x05, 0xb2, 0xaf, 0x51, 0x57, 0x7c, 0x5b, 0x33, 0x7c, 0x0e, 0xda, 0x9a, 0xa7, 0x71,
	0x91, 0xf5, 0x65, 0x9e, 0xac, 0x79, 0x3a, 0xcf, 0x8c, 0x37, 0x70, 0xe1, 0xb0, 0x61, 0x33, 0x47,
	0xb8, 0xdf, 0x0a, 0xe8, 0x3b, 0xb0, 0x57, 0xfc, 0x08, 0x5a, 0x2d, 0x13, 0xd9, 0xd4, 0x2d, 0xa9,
	0x4f, 0x5f, 0x0f, 0x3b, 0xfb, 0x97, 0x35, 0x83, 0x16, 0xa4, 0x7d, 0x02, 0xde, 0xc0, 0xb8, 0xd8,
	0x24, 0x39, 0x8b, 0x1b, 0x51, 0xb6, 0x73, 0x8d, 0xe9, 0xa8, 0x0d, 0x44, 0xa2, 0x34, 0xee, 0x41,
	0xeb, 0x70, 0x44, 0xd0, 0x23, 0x77, 0xe1, 0x7a, 0xdf, 0xdd, 0x38, 0x08, 0x1f, 0xc2, 0x28, 0x20,
	0x27, 0xf8, 0x14, 0xce, 0x7d, 0xdb, 0xb5, 0xe6, 0xae, 0x43, 0x14, 0x1c, 0xc1, 0x99, 0xe5, 0xb9,
	0x36, 0x51, 0x11, 0x40, 0xfb, 0xf2, 0x30, 0xff, 0x66, 0x5b, 0xe4, 0xf4, 0xdd, 0x67, 0x38, 0xef,
	0x8d, 0xc1, 0x4b, 0x98, 0xec, 0x14, 0x7c, 0xea, 0x59, 0xd1, 0x2c, 0x24, 0x27, 0x7f, 0xb3, 0x1c,
	0xea, 0xcf, 0x88, 0x82, 0x3a, 0xc0, 0x22, 0x7a, 0xb4, 0xa9, 0x6b, 0x87, 0x76, 0x40, 0x54, 0xd4,
	0x40, 0x75, 0x3c, 0x72, 0x3a, 0xfd, 0xa5, 0x00, 0x38, 0xc5, 0x6a, 0xd6, 0x6d, 0x11, 0x6d, 0x18,
	0xed, 0xfc, 0xc4, 0x9b, 0xe1, 0x94, 0xff, 0x6d, 0xf2, 0xfa, 0xd5, 0xe1, 0xcf, 0xde, 0xb0, 0x7b,
	0xd0, 0x3a, 0x5b, 0xf0, 0xe5, 0x21, 0xab, 0x3a, 0x89, 0xeb, 0xe3, 0x2e, 0x3e, 0x3e, 0xfb, 0x31,
	0xb8, 0xa4, 0x54, 0x6b, 0x8f, 0xeb, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x9d, 0x88,
	0xb1, 0x76, 0x02, 0x00, 0x00,
}
